version: '3.9'
services:
  app:
    build: .
  proxy:
    image: nginx:latest
    volumes:
      - "$PWD/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "$PWD/secure.localhost.pem:/secrets/secure.localhost.pem:ro"
      - "$PWD/secure.localhost-key.pem:/secrets/secure.localhost-key.pem:ro"
    ports:
      - 8081:443
