version: '3.9'
services:
  app:
    build: .
    # Expose the app port directly for debugging. The intention is that access
    # will be via the NGINX reverse proxy.
    ports:
      - 8501:8501
    environment:
      - STREAMLIT_BROWSER_SERVER_ADDRESS
  proxy:
    image: nginx:1.21.5-alpine
    volumes:
      - "$PWD/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "$PWD/streamlit-demo.pem:/secrets/streamlit-demo.pem:ro"
      - "$PWD/streamlit-demo-key.pem:/secrets/streamlit-demo-key.pem:ro"
    ports:
      - 8502:8502
