version: "3.9"
services:
  app:
    build: .
    # Uncomment the ports section to expose the app port directly, for
    # debugging. The intention is that access will be via the reverse proxy.
    #
    # ports:
    #   - 8501:8501
    labels:
      # Create a basic auth middleware called test-auth. user1's password is "password".
      #
      # To create a new username/password entry:
      #
      #   htpasswd -nb user1 password | sed -e "s/\\\$/\$\$/g"
      - "traefik.http.middlewares.test-auth.basicauth.users=user1:$$apr1$$XnxcGrAf$$AjOI2dWap6YsZn/q69GTu0"
      # Apply the test-auth middleware to the app router
      - "traefik.http.routers.app.middlewares=test-auth"
      - "traefik.http.routers.app.rule=Host(`localhost.shiftlab.cloud`)"
      - "traefik.http.routers.app.tls=true"

  traefik:
    image: traefik:v2.6
    command:
      - --api.insecure=true
      - --entrypoints.web-secure.address=:443
      - --providers.docker=true
      - --providers.file.directory=/config/
      - --providers.file.watch=true
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "$PWD:/config/"
