version: '3.9'
services:
  app:
    build: .
    # Expose the app port directly for debugging. The intention is that access
    # will be via the NGINX reverse proxy.
    ports:
      - 8501:8501
  proxy:
    image: nginx:latest
    volumes:
      - "$PWD/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - 8080:80
