version: "3.9"
services:
  app:
    build: .
    # Uncomment the ports section to expose the app port directly, for
    # debugging. The intention is that access will be via the reverse proxy.
    #
    # ports:
    #   - 8501:8501
    labels:
      - "traefik.http.routers.app.rule=Host(`localhost.dev.shiftlab.ai`)"
      - "traefik.http.routers.app.tls=true"

  traefik:
    image: traefik:v2.6
    command:
      - --api.insecure=true
      - --entrypoints.web-secure.address=:443
      - --providers.docker=true
      - --providers.file.directory=/config/
      - --providers.file.watch=true
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "$PWD:/config/"
